USE robotoDB;

DROP TABLE IF EXISTS tracksPlayed;
CREATE TABLE tracksPlayed (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    artistID INT UNSIGNED NOT NULL,
    trackID INT UNSIGNED NOT NULL,
    whenPlayed DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    djID CHAR(24) NOT NULL
);

DROP TABLE IF EXISTS artists;
CREATE TABLE artists (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    artistName TEXT NOT NULL,
    displayArtistsID INT UNSIGNED
);

DROP TABLE IF EXISTS displayArtists;
CREATE TABLE displayArtists (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    displayArtist TEXT NOT NULL
);

DROP TABLE IF EXISTS tracks;
CREATE TABLE tracks (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    trackName TEXT NOT NULL,
    displayTracksID INT UNSIGNED
);

DROP TABLE IF EXISTS displayTracks;
CREATE TABLE displayTracks (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    displayTrack TEXT NOT NULL
);

