USE robotoDB;

CREATE TABLE IF NOT EXISTS tracks (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    artistID INT UNSIGNED NOT NULL,
    trackID INT UNSIGNED NOT NULL,
    whenPlayed DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    djID CHAR(24) NOT NULL
);

CREATE TABLE IF NOT EXISTS artists (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    artistName TEXT NOT NULL,
    displayArtistsID INT UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS displayArtists (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    displayArtist TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS tracks (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    trackName TEXT NOT NULL,
    displayTracksID INT UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS displayTracks (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    displayTrack TEXT NOT NULL
);

